[package]
name = "vbsp"
version = "0.9.1"
authors = ["Robin Appelman <robin@icewind.nl>"]
homepage = "https://github.com/icewind1991/vbsp"
repository = "https://github.com/icewind1991/vbsp"
description = "Rust parser for valve bsp files."
license = "MIT"
edition = "2024"
readme = "README.md"
exclude = ["*.bsp"]
rust-version = "1.85.0"

[features]
default = ["zip"]
zip = ["dep:zip"]

[dependencies]
vbsp-common = { version = "0.1.0", path = "common" }
arrayvec = "0.7.6"
bitflags = "2.9.0"
bv = "0.11.1"
thiserror = "2.0.11"
lzma-rs = "0.3.0"
binrw = "0.14.1"
static_assertions = "1.1.0"
num_enum = "0.7.3"
zip = { version = "2.6.1", default-features = false, features = ["lzma"], optional = true }
itertools = "0.14.0"
ahash = "0.8.12"
serde = "1.0.219"
vdf-reader = "0.3.0"

[dev-dependencies]
obj = "0.10"
main_error = "0.1.2"
criterion = "0.5.1"
vbsp-entities-tf2 = { version = "0.1.0-egg" }

[profile.dev]
opt-level = 2

[[bench]]
name = "bench"
harness = false

[workspace]
members = ["common"]
